# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
digital_ocean_memory = 1024

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "development", primary: true do |dev|
    dev.vm.network "private_network", ip: "192.168.50.60"
    dev.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: false
    dev.vm.network :forwarded_port, guest: 3000, host: 3000, id: "app", auto_correct: false

    dev.vm.synced_folder "../", "/var/stonecutter"

    dev.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", 2048]
    end

    dev.vm.provision "ansible" do |ansible|
      ansible.playbook = "development_playbook.yml"
      ansible.inventory_path = "development.inventory"
      ansible.sudo = true
    end
  end

  config.vm.define "dob_vm", primary: true do |dob|
    dob.vm.network "private_network", ip: "192.168.50.61"
    dob.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct: false

    dob.vm.provider "virtualbox" do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", digital_ocean_memory, "--cpus", 1]
    end

    dob.vm.provision "ansible" do |ansible|
      ansible.playbook = "dob_vm_playbook.yml"
      ansible.inventory_path = "dob_vm.inventory"
      ansible.sudo = true
    end

    dob.vm.synced_folder "../", "/var/stonecutter"
  end

end
